package apps.somniac.fightme.exceptions.messages;

public class DataErrorMessages {

	// ----- ERRORES --------------------------------------------------------------------------------------------------------------

	public static final String USER_NO_CONTENT = "El usuario especificado no está registrado en la base de datos.";
	public static final String CHARACTER_NO_CONTENT = "El personaje especificado no está registrado en la base de datos.";
	public static final String SKILL_NO_CONTENT = "La habilidad especificada no está registrada en la base de datos.";
	public static final String CHARACTER_ROL_NO_CONTENT = "El rol especificado no está registrado en la base de datos.";
	public static final String IMG_NO_CONTENT = "No existe ninguna imagen asociada a la clase especificada. Se usará la imagen por defecto.";
	public static final String ROLE_NO_CONTENT = "El rol especificado no está registrado en la base de datos.";
	public static final String PERSONID_NO_CONTENT = "El personId especificado no está registrado en la base de datos.";
	public static final String IMAGE_NO_CONTENT = "Ha ocurrido un error al subir la imagen al soporte de FaceId.";
	public static final String GENERIC_NO_CONTENT = "Ha ocurrido un error al acceder al soporte de FaceId.";

	public static final String USERNAME_ALREADY_BEEN_USED = "El nombre de usuario indicado ya está siendo utilizado.";
	public static final String EMAIL_ALREADY_BEEN_USED = "La dirección de correo indicada ya está siendo utilizada.";
	public static final String CHARACTERNAME_ALREADY_BEEN_USED = "El nombre indicado ya está siendo utilizado por otro personaje.";
	public static final String FAIL_TO_UPLOAD_FILE = "Se ha producido un error al subir el archivo";
	
	public static final String GAME_OVER = "GAME OVER";

}
